// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjWJlTy_cjzBANO8LGCFlZ1xi9kAV1a3Q',
    appId: '1:817174326423:web:85b9b115f6f44c27e60dd2',
    messagingSenderId: '817174326423',
    projectId: 'vacationz-95f43',
    authDomain: 'vacationz-95f43.firebaseapp.com',
    storageBucket: 'vacationz-95f43.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeRyrlQfosCK-PaaYgBh5_mFOyvyq9wdY',
    appId: '1:817174326423:android:296ac16a55a736afe60dd2',
    messagingSenderId: '817174326423',
    projectId: 'vacationz-95f43',
    storageBucket: 'vacationz-95f43.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWDFL0JsE_SNZHJPCO8Is6Kk_licB_LNE',
    appId: '1:817174326423:ios:2e979c1ee0239373e60dd2',
    messagingSenderId: '817174326423',
    projectId: 'vacationz-95f43',
    storageBucket: 'vacationz-95f43.appspot.com',
    iosBundleId: 'com.example.mobpro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWDFL0JsE_SNZHJPCO8Is6Kk_licB_LNE',
    appId: '1:817174326423:ios:94dfbecb5d90372de60dd2',
    messagingSenderId: '817174326423',
    projectId: 'vacationz-95f43',
    storageBucket: 'vacationz-95f43.appspot.com',
    iosBundleId: 'com.example.mobpro.RunnerTests',
  );
}
